{% set name = "python-flatbuffers" %}
{% set pypi_name = "flatbuffers" %}
{% set version = "24.3.25" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://pypi.io/packages/source/{{ pypi_name[0] }}/{{ pypi_name }}/{{ pypi_name }}-{{ version }}.tar.gz
  sha256: de2ec5b203f21441716617f38443e0a8ebf3d25bf0d9c0bb0ce68fa00ad546a4

build:
  number: 0
  script: {{ PYTHON }} -m pip install . --no-deps --no-build-isolation -vv

requirements:
  host:
    - python
    - pip
    - setuptools
    - wheel
  run:
    - python

test:
  requires:
    - pip
  commands:
    - pip check
  imports:
    - flatbuffers
    - flatbuffers.builder
    - flatbuffers.table

about:
  home: https://flatbuffers.dev/
  license: Apache-2.0
  license_family: Apache
  license_file: LICENSE.txt
  summary: The FlatBuffers serialization format for Python
  description: |
    FlatBuffers is an efficient cross platform serialization library for C++, C#, C, Go, Java, JavaScript, Lobster, Lua, TypeScript, PHP, Python, and Rust. It was originally created at Google for game development and other performance-critical applications. This package is the python runtime library. The flatc compiler is in the flatbuffers conda package.
  doc_url: https://flatbuffers.dev/
  dev_url: https://github.com/google/flatbuffers

extra:
  recipe-maintainers:
    - kalefranz
    - njzjz
    - xhochy
